"""add SOFA lab columns to vital_sign

Revision ID: 33909c9d8845
Revises: 0002
Create Date: 2026-06-26 14:31:34.029473

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = "33909c9d8845"
down_revision: Union[str, None] = "0002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "alert",
        "status",
        existing_type=sa.VARCHAR(length=16),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_index(op.f("alert_created_at_idx"), table_name="alert")
    op.drop_index(op.f("clinical_score_calculated_at_idx"), table_name="clinical_score")
    op.alter_column(
        "patient_cache",
        "is_active",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "is_admin",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "is_active",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_unique_constraint(None, "users", ["email"])
    op.add_column(
        "vital_sign", sa.Column("pao2_fio2", sa.Numeric(precision=8, scale=2), nullable=True)
    )
    op.add_column("vital_sign", sa.Column("mechanical_ventilation", sa.Boolean(), nullable=True, server_default=sa.text("false")))
    op.add_column(
        "vital_sign", sa.Column("platelets", sa.Numeric(precision=8, scale=1), nullable=True)
    )
    op.add_column(
        "vital_sign", sa.Column("bilirubin", sa.Numeric(precision=8, scale=2), nullable=True)
    )
    op.add_column(
        "vital_sign", sa.Column("map_value", sa.Numeric(precision=6, scale=1), nullable=True)
    )
    op.add_column("vital_sign", sa.Column("vasopressor_type", sa.String(length=32), nullable=True))
    op.add_column(
        "vital_sign",
        sa.Column("vasopressor_dose_mcg_kg_min", sa.Numeric(precision=8, scale=3), nullable=True),
    )
    op.add_column("vital_sign", sa.Column("gcs", sa.Integer(), nullable=True))
    op.add_column(
        "vital_sign", sa.Column("creatinine", sa.Numeric(precision=8, scale=2), nullable=True)
    )
    op.add_column(
        "vital_sign",
        sa.Column("urine_output_ml_day", sa.Numeric(precision=10, scale=1), nullable=True),
    )
    op.drop_index(op.f("vital_sign_recorded_at_idx"), table_name="vital_sign")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("vital_sign_recorded_at_idx"),
        "vital_sign",
        [sa.literal_column("recorded_at DESC")],
        unique=False,
    )
    op.drop_column("vital_sign", "urine_output_ml_day")
    op.drop_column("vital_sign", "creatinine")
    op.drop_column("vital_sign", "gcs")
    op.drop_column("vital_sign", "vasopressor_dose_mcg_kg_min")
    op.drop_column("vital_sign", "vasopressor_type")
    op.drop_column("vital_sign", "map_value")
    op.drop_column("vital_sign", "bilirubin")
    op.drop_column("vital_sign", "platelets")
    op.drop_column("vital_sign", "mechanical_ventilation")
    op.drop_column("vital_sign", "pao2_fio2")
    op.drop_constraint(None, "users", type_="unique")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.alter_column(
        "users",
        "is_active",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "is_admin",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.alter_column(
        "patient_cache",
        "is_active",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_nullable=False,
    )
    op.create_index(
        op.f("clinical_score_calculated_at_idx"),
        "clinical_score",
        [sa.literal_column("calculated_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("alert_created_at_idx"), "alert", [sa.literal_column("created_at DESC")], unique=False
    )
    op.alter_column(
        "alert",
        "status",
        existing_type=sa.VARCHAR(length=16),
        server_default=sa.text("'active'::character varying"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
